# Generated by Django 4.1.13 on 2023-11-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0004_remove_purchaseorder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0),
        ),
    ]
