# Generated by Django 4.1.13 on 2023-11-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_title', models.CharField(max_length=25)),
                ('api_desc', models.TextField(max_length=100)),
                ('api_url', models.CharField(max_length=25)),
                ('api_method', models.CharField(max_length=7)),
                ('api_params', models.TextField(max_length=150)),
            ],
        ),
    ]
