# Generated by Django 4.1.13 on 2023-12-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apis',
            options={'verbose_name': 'API', 'verbose_name_plural': 'APIs'},
        ),
        migrations.AlterField(
            model_name='apis',
            name='api_desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='apis',
            name='api_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apis',
            name='api_url',
            field=models.CharField(max_length=100),
        ),
    ]
